<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="Configurations\**" />
	  <Compile Remove="Middlewares\**" />
	  <Content Remove="Configurations\**" />
	  <Content Remove="Middlewares\**" />
	  <EmbeddedResource Remove="Configurations\**" />
	  <EmbeddedResource Remove="Middlewares\**" />
	  <None Remove="Configurations\**" />
	  <None Remove="Middlewares\**" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\2.Core\CapitalUniversity.Core.Application\CapitalUniversity.Core.Application.csproj" />
		<ProjectReference Include="..\..\2.Core\CapitalUniversity.Core.Infrastructure\CapitalUniversity.Core.Infrastructure.csproj" />
		<ProjectReference Include="..\..\4.Modules\CapitalUniversity.Module.Payments.Abstractions\CapitalUniversity.Module.Payments.Abstractions.csproj" />
		<ProjectReference Include="..\..\4.Modules\CapitalUniversity.Module.Payments\CapitalUniversity.Module.Payments.csproj" />
		<ProjectReference Include="..\..\4.Modules\CapitalUniversity.Module.Student.Abstractions\CapitalUniversity.Module.Student.Abstractions.csproj" />
		<ProjectReference Include="..\..\4.Modules\CapitalUniversity.Module.StudentServices\CapitalUniversity.Module.StudentServices.csproj" />
		<ProjectReference Include="..\..\4.Modules\CapitalUniversity.Module.Student\CapitalUniversity.Module.Student.csproj" />
		<ProjectReference Include="..\..\4.Modules\CapitalUniversity.Module.CourseOffering.Abstractions\CapitalUniversity.Module.CourseOffering.Abstractions.csproj" />
		<ProjectReference Include="..\..\4.Modules\CapitalUniversity.Module.CourseOffering\CapitalUniversity.Module.CourseOffering.csproj" />
		<ProjectReference Include="..\..\4.Modules\CapitalUniversity.Module.Registration.Abstractions\CapitalUniversity.Module.Registration.Abstractions.csproj" />
		<ProjectReference Include="..\..\4.Modules\CapitalUniversity.Module.Registration\CapitalUniversity.Module.Registration.csproj" />
		<ProjectReference Include="..\..\4.Modules\CapitalUniversity.Module.AcademicRecords.Abstractions\CapitalUniversity.Module.AcademicRecords.Abstractions.csproj" />
		<ProjectReference Include="..\..\4.Modules\CapitalUniversity.Module.AcademicRecords\CapitalUniversity.Module.AcademicRecords.csproj" />
		<ProjectReference Include="..\..\4.Modules\CapitalUniversity.Module.Schedule.Abstractions\CapitalUniversity.Module.Schedule.Abstractions.csproj" />
		<ProjectReference Include="..\..\4.Modules\CapitalUniversity.Module.Schedule\CapitalUniversity.Module.Schedule.csproj" />
	</ItemGroup>
</Project>
