<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <RootNamespace>CapitalUniversity.Core.Domain</RootNamespace>
  </PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\CapitalUniversity.Core.Abstractions\CapitalUniversity.Core.Abstractions.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="MongoDB.Bson" Version="3.8.0" />
	</ItemGroup>

</Project>
