<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.0" />
		<PackageReference Include="StackExchange.Redis" Version="2.7.27" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.9" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.0" />
		<PackageReference Include="MongoDB.Driver" Version="3.8.0" />
		<PackageReference Include="Riok.Mapperly" Version="5.0.0-next.7" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\CapitalUniversity.Core.Application\CapitalUniversity.Core.Application.csproj" />
		<ProjectReference Include="..\CapitalUniversity.Core.Domain\CapitalUniversity.Core.Domain.csproj" />
		<ProjectReference Include="..\CapitalUniversity.Core.Abstractions\CapitalUniversity.Core.Abstractions.csproj" />
	</ItemGroup>
</Project>