import React, { useState, useEffect } from "react";
import { useParams } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { DollarSign, Calendar, MapPin, Layers, ToggleRight, FileText } from "lucide-react";
import { getServiceById } from "../../services/studentServicesService";
import LoadingSpinner from "../../components/LoadingSpinner";
import "../../styles/admin/ServiceDetailsPage.css";

const ServiceDetailsPage = () => {
  const { id } = useParams(); const { t } = useTranslation(); const [service, setService] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(null); const [activeTab, setActiveTab] = useState("info");
  useEffect(() => { loadService(); }, [id]);
  const loadService = async () => { setLoading(true); try { const data = await getServiceById(id); setService(data); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  const getServiceTypeLabel = (type) => { if (typeof type === "number") { const types = { 1: "General", 2: "Specialized", 3: "Administrative" }; type = types[type] || "General"; } const labels = { General: t("general"), Specialized: t("specialized"), Administrative: t("administrative") }; return labels[type] || type; };
  if (loading) return <LoadingSpinner />; if (error) return <div className="sdp-error">{error}</div>; if (!service) return <div className="sdp-error">{t("service_not_found")}</div>;
  const hasWorkflow = service.workflow?.steps?.length > 0;
  return (
    <div className="sdp">
      <div className="sdp-hero"><div className="sdp-hero-left"><div className="sdp-hero-name">{service.name}</div><div className="sdp-hero-badges"><span className="sdp-hbadge sdp-hb-type"><span className="sdp-dot" />{getServiceTypeLabel(service.type)}</span><span className={`sdp-hbadge ${service.isActive ? "sdp-hb-active" : "sdp-hb-inactive"}`}><span className="sdp-dot" />{service.isActive ? t("active") : t("inactive")}</span><span className={`sdp-hbadge ${service.isPaid ? "sdp-hb-paid" : "sdp-hb-free"}`}>{service.isPaid ? `$${service.price}` : t("free")}</span></div></div>
      <div className="sdp-hero-right">{(service.academicYearName || service.academicYearId) && (<div className="sdp-stat-pill"><span>{t("academic_year")}</span><strong>{service.academicYearName || service.academicYearId}</strong></div>)}{(service.semesterName || service.semesterId) && (<div className="sdp-stat-pill"><span>{t("semester")}</span><strong>{service.semesterName || service.semesterId}</strong></div>)}{hasWorkflow && (<div className="sdp-stat-pill"><span>{t("workflow_steps")}</span><strong>{service.workflow.steps.length} steps</strong></div>)}</div></div>
      <div className="sdp-body"><div className="sdp-tabs-row"><button className={`sdp-tab${activeTab==="info"?" sdp-tab-active":""}`} onClick={()=>setActiveTab("info")}>{t("info")||"Info"}</button><button className={`sdp-tab${activeTab==="scope"?" sdp-tab-active":""}`} onClick={()=>setActiveTab("scope")}>{t("structural_scope")}</button><button className={`sdp-tab${activeTab==="workflow"?" sdp-tab-active":""}`} onClick={()=>setActiveTab("workflow")}>{t("workflow_steps")}</button></div>
      {activeTab==="info" && (<div className="sdp-card sdp-fade"><div className="sdp-sec-title">{t("service_details")}</div><div className="sdp-info-grid"><div className="sdp-info-item sdp-full"><div className="sdp-info-icon"><FileText size={14} /></div><div><span className="sdp-info-label">{t("description")}</span><span className="sdp-info-value sdp-muted">{service.description || t("no_description")}</span></div></div><div className="sdp-info-item"><div className="sdp-info-icon"><DollarSign size={14} /></div><div><span className="sdp-info-label">{t("pricing")}</span><span className="sdp-info-value">{service.isPaid ? `$${service.price}` : t("free")}</span></div></div><div className="sdp-info-item"><div className="sdp-info-icon"><Layers size={14} /></div><div><span className="sdp-info-label">{t("type")}</span><span className="sdp-info-value">{getServiceTypeLabel(service.type)}</span></div></div>{service.academicYearId && (<div className="sdp-info-item"><div className="sdp-info-icon"><Calendar size={14} /></div><div><span className="sdp-info-label">{t("academic_year")}</span><span className="sdp-info-value">{service.academicYearName || service.academicYearId}</span></div></div>)}{service.semesterId && (<div className="sdp-info-item"><div className="sdp-info-icon"><Calendar size={14} /></div><div><span className="sdp-info-label">{t("semester")}</span><span className="sdp-info-value">{service.semesterName || service.semesterId}</span></div></div>)}<div className="sdp-info-item"><div className="sdp-info-icon"><ToggleRight size={14} /></div><div><span className="sdp-info-label">{t("status")}</span><span className="sdp-info-value">{service.isActive ? t("active") : t("inactive")}</span></div></div></div></div>)}
      {activeTab==="scope" && (<div className="sdp-card sdp-fade"><div className="sdp-sec-title">{t("structural_scope")}</div><div className="sdp-info-grid"><div className="sdp-info-item sdp-full"><div className="sdp-info-icon"><MapPin size={14} /></div><div><span className="sdp-info-label">{t("assigned_nodes") || "Assigned Nodes"}</span><div className="sdp-scope-list">{service.scopeNodesDetails?.length > 0 ? service.scopeNodesDetails.map(node => (<span key={node.id} className="sdp-scope-tag">{node.localizedName}</span>)) : <span className="sdp-info-value">{t("global_scope")}</span>}</div>{service.includeDescendants && (<span className="sdp-hint">{t("include_descendants")}</span>)}</div></div></div></div>)}
      {activeTab==="workflow" && (<div className="sdp-card sdp-fade"><div className="sdp-sec-title">{t("workflow_steps")}</div>{hasWorkflow ? (<div className="sdp-step-list">{service.workflow.steps.map((step,idx) => (<div key={idx} className="sdp-step"><div className="sdp-step-num">{idx+1}</div><span className="sdp-step-title">{step.title}</span>{step.isRequired && <span className="sdp-step-req">{t("required")}</span>}</div>))}</div>) : <p className="sdp-empty">{t("no_workflow_steps")}</p>}</div>)}</div>
    </div>
  );
};

export default ServiceDetailsPage;