import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import {
  User, Mail, Lock, Phone, Shield, CheckCircle2, UserPlus, KeyRound,
  Building2, Briefcase, Calendar, Hash
} from "lucide-react";
import userService from "../services/userService";
import { ScopeTreeModal } from "../../university/components/ScopeTreeModal";
import "../styles/userForms.css";

const AddStaff = () => {
  const navigate = useNavigate();
  const steps = ["Basic Information", "Account Security", "Employment Information"];
  const [currentStep, setCurrentStep] = useState(0);
  const [loading, setLoading] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [showSuccess, setShowSuccess] = useState(false);
  const [showStructureModal, setShowStructureModal] = useState(false);

  const [formData, setFormData] = useState({
    staffCode: "",
    nationalId: "",
    name: "",
    email: "",
    password: "",
    confirmPassword: "",
    role: "",
    jobTitle: "",
    structureNodeId: "",
    phoneNumber: "",
    birthDate: "",
  });

  const [roles, setRoles] = useState([]);
  const [autoGeneratedCode, setAutoGeneratedCode] = useState("");
  const [selectedNodeName, setSelectedNodeName] = useState("");
  const [errors, setErrors] = useState({});
  const [checkingEmail, setCheckingEmail] = useState(false);
  const [checkingNationalId, setCheckingNationalId] = useState(false);

  useEffect(() => {
    const loadRoles = async () => {
      setLoading(true);
      try {
        const rolesData = await userService.getRoles();
        setRoles(rolesData);
        setAutoGeneratedCode(`EMP-${Date.now()}`);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    loadRoles();
  }, []);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
    if (errors[name]) setErrors((prev) => ({ ...prev, [name]: "" }));
  };

  const handleNodeSelect = (node) => {
    setFormData((prev) => ({ ...prev, structureNodeId: node.id }));
    setSelectedNodeName(`${node.name} (${node.type})`);
    setShowStructureModal(false);
    if (errors.structureNodeId) setErrors((prev) => ({ ...prev, structureNodeId: "" }));
  };

  const checkEmailUnique = async (email) => {
    if (!email) return true;
    setCheckingEmail(true);
    try {
      const result = await userService.checkEmailUnique(email, "Staff");
      return result.isUnique;
    } catch {
      return false;
    } finally {
      setCheckingEmail(false);
    }
  };

  const checkNationalIdUnique = async (nationalId) => {
    if (!nationalId) return true;
    setCheckingNationalId(true);
    try {
      const result = await userService.checkNationalIdUnique(nationalId, "Staff");
      return result.isUnique;
    } catch {
      return false;
    } finally {
      setCheckingNationalId(false);
    }
  };

  const validateStep = async () => {
    const newErrors = {};
    if (currentStep === 0) {
      if (!formData.nationalId) newErrors.nationalId = "National ID is required";
      else if (formData.nationalId.length !== 14) newErrors.nationalId = "Must be 14 digits";
      else if (!/^\d+$/.test(formData.nationalId)) newErrors.nationalId = "Only numbers allowed";
      else {
        const unique = await checkNationalIdUnique(formData.nationalId);
        if (!unique) newErrors.nationalId = "National ID already exists";
      }
      if (!formData.name) newErrors.name = "Full name is required";
      if (!formData.email) newErrors.email = "Email is required";
      else if (!/\S+@\S+\.\S+/.test(formData.email)) newErrors.email = "Invalid email format";
      else {
        const unique = await checkEmailUnique(formData.email);
        if (!unique) newErrors.email = "Email already exists";
      }
      if (!formData.birthDate) newErrors.birthDate = "Date of birth is required";
    }
    if (currentStep === 1) {
      if (!formData.password) newErrors.password = "Password is required";
      else if (formData.password.length < 6) newErrors.password = "At least 6 characters";
      if (formData.password !== formData.confirmPassword)
        newErrors.confirmPassword = "Passwords do not match";
    }
    if (currentStep === 2) {
      if (!formData.role) newErrors.role = "Role is required";
      if (!formData.structureNodeId)
        newErrors.structureNodeId = "Structure node (Faculty/Department) is required";
    }
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const nextStep = async () => {
    if (await validateStep()) setCurrentStep((prev) => prev + 1);
  };
  const prevStep = () => setCurrentStep((prev) => prev - 1);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!(await validateStep())) return;
    setSubmitting(true);
    const finalEmployeeCode = formData.staffCode.trim() || autoGeneratedCode;
    const payload = {
      employeeCode: finalEmployeeCode,
      name: formData.name,
      nationalId: formData.nationalId,
      birthDate: formData.birthDate,
      phoneNumber: formData.phoneNumber || null,
      email: formData.email,
      password: formData.password,
      confirmPassword: formData.confirmPassword,
      role: formData.role,
      jobTitle: formData.jobTitle || null,
      structureNodeId: formData.structureNodeId,
    };
    try {
      await userService.createStaff(payload);
      setShowSuccess(true);
      setTimeout(() => navigate("/admin/users"), 1600);
    } catch (err) {
      alert(err.response?.data?.message || err.message);
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) return <div className="form-loading">Loading...</div>;

  return (
    <div className="add-user-page">
      <div className="page-container compact-wizard">
        <div className="page-header compact-header">
          <div className="header-content">
            <div className="header-icon"><UserPlus size={22} /></div>
            <div className="header-text">
              <h1>Add New Staff Member</h1>
              <div className="gold-line" />
              <p>Create a new staff account step by step</p>
            </div>
          </div>
        </div>

        <div className="wizard-steps">
          {steps.map((step, idx) => (
            <button
              key={step}
              type="button"
              className={`wizard-step ${idx === currentStep ? "active" : ""} ${
                idx < currentStep ? "done" : ""
              }`}
              onClick={() => setCurrentStep(idx)}
            >
              <span>{idx + 1}</span>
              {step}
            </button>
          ))}
        </div>

        <form onSubmit={handleSubmit}>
          {/* Step 0: Basic Information */}
          {currentStep === 0 && (
            <div className="form-card wizard-card">
              <div className="form-header">
                <div className="form-icon"><User size={18} color="#e0c06a" /></div>
                <div className="form-title-wrapper"><h3>Basic Information</h3><p>Personal details</p></div>
              </div>
              <div className="form-body">
                <div className="form-grid compact-grid">
                  <div className="form-group">
                    <label className="form-label">National ID *</label>
                    <div className="input-wrapper">
                      <input
                        type="text"
                        name="nationalId"
                        value={formData.nationalId}
                        onChange={handleChange}
                        className={`form-input ${errors.nationalId ? "error" : ""}`}
                        placeholder="14-digit national ID"
                        maxLength="14"
                      />
                      <User size={15} className="input-icon" />
                    </div>
                    {checkingNationalId && <span className="input-hint">Checking...</span>}
                    {errors.nationalId && <span className="error-message">{errors.nationalId}</span>}
                  </div>

                  <div className="form-group">
                    <label className="form-label">Full Name *</label>
                    <div className="input-wrapper">
                      <input
                        type="text"
                        name="name"
                        value={formData.name}
                        onChange={handleChange}
                        className={`form-input ${errors.name ? "error" : ""}`}
                        placeholder="Full name"
                      />
                      <User size={15} className="input-icon" />
                    </div>
                    {errors.name && <span className="error-message">{errors.name}</span>}
                  </div>

                  <div className="form-group">
                    <label className="form-label">Email *</label>
                    <div className="input-wrapper">
                      <input
                        type="email"
                        name="email"
                        value={formData.email}
                        onChange={handleChange}
                        className={`form-input ${errors.email ? "error" : ""}`}
                        placeholder="staff@university.edu"
                      />
                      <Mail size={15} className="input-icon" />
                    </div>
                    {checkingEmail && <span className="input-hint">Checking...</span>}
                    {errors.email && <span className="error-message">{errors.email}</span>}
                  </div>

                  <div className="form-group">
                    <label className="form-label">Date of Birth *</label>
                    <div className="input-wrapper">
                      <input
                        type="date"
                        name="birthDate"
                        value={formData.birthDate}
                        onChange={handleChange}
                        className={`form-input ${errors.birthDate ? "error" : ""}`}
                      />
                      <Calendar size={15} className="input-icon" />
                    </div>
                    {errors.birthDate && <span className="error-message">{errors.birthDate}</span>}
                  </div>

                  <div className="form-group">
                    <label className="form-label">Phone</label>
                    <div className="input-wrapper">
                      <input
                        type="tel"
                        name="phoneNumber"
                        value={formData.phoneNumber}
                        onChange={handleChange}
                        className="form-input"
                        placeholder="Phone number"
                      />
                      <Phone size={15} className="input-icon" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Step 1: Account Security */}
          {currentStep === 1 && (
            <div className="form-card wizard-card">
              <div className="form-header">
                <div className="form-icon"><KeyRound size={18} color="#e0c06a" /></div>
                <div className="form-title-wrapper"><h3>Account Security</h3><p>Set password</p></div>
              </div>
              <div className="form-body">
                <div className="form-grid compact-grid two-cols">
                  <div className="form-group">
                    <label className="form-label">Password *</label>
                    <div className="input-wrapper">
                      <input
                        type="password"
                        name="password"
                        value={formData.password}
                        onChange={handleChange}
                        className={`form-input ${errors.password ? "error" : ""}`}
                        placeholder="Minimum 6 characters"
                      />
                      <Lock size={15} className="input-icon" />
                    </div>
                    {errors.password && <span className="error-message">{errors.password}</span>}
                  </div>
                  <div className="form-group">
                    <label className="form-label">Confirm Password *</label>
                    <div className="input-wrapper">
                      <input
                        type="password"
                        name="confirmPassword"
                        value={formData.confirmPassword}
                        onChange={handleChange}
                        className={`form-input ${errors.confirmPassword ? "error" : ""}`}
                        placeholder="Re-enter password"
                      />
                      <Lock size={15} className="input-icon" />
                    </div>
                    {errors.confirmPassword && <span className="error-message">{errors.confirmPassword}</span>}
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Step 2: Employment Information */}
          {currentStep === 2 && (
            <div className="form-card wizard-card">
              <div className="form-header">
                <div className="form-icon"><Briefcase size={18} color="#e0c06a" /></div>
                <div className="form-title-wrapper"><h3>Employment Information</h3><p>Role, job title, structure node, and staff code</p></div>
              </div>
              <div className="form-body">
                <div className="form-grid compact-grid">
                  <div className="form-group">
                    <label className="form-label">Staff Code</label>
                    <div className="input-wrapper">
                      <input
                        type="text"
                        name="staffCode"
                        value={formData.staffCode}
                        onChange={handleChange}
                        className="form-input"
                        placeholder="Leave empty to auto-generate"
                      />
                      <Hash size={15} className="input-icon" />
                    </div>
                    <span className="input-hint">Optional; will be auto-generated if left empty</span>
                  </div>

                  <div className="form-group">
                    <label className="form-label">Role *</label>
                    <div className="input-wrapper">
                      <select
                        name="role"
                        value={formData.role}
                        onChange={handleChange}
                        className={`form-select ${errors.role ? "error" : ""}`}
                      >
                        <option value="">Select Role</option>
                        {roles.map((r) => (
                          <option key={r.id} value={r.id}>{r.name}</option>
                        ))}
                      </select>
                      <Shield size={15} className="input-icon" />
                    </div>
                    {errors.role && <span className="error-message">{errors.role}</span>}
                  </div>

                  <div className="form-group">
                    <label className="form-label">Job Title</label>
                    <div className="input-wrapper">
                      <input
                        type="text"
                        name="jobTitle"
                        value={formData.jobTitle}
                        onChange={handleChange}
                        className="form-input"
                        placeholder="e.g., Department Head"
                      />
                      <Briefcase size={15} className="input-icon" />
                    </div>
                  </div>

                  <div className="form-group">
                    <label className="form-label">Structure Node (Faculty/Department) *</label>
                    <div className="input-wrapper">
                      <input
                        type="text"
                        value={selectedNodeName}
                        readOnly
                        onClick={() => setShowStructureModal(true)}
                        className={`form-input ${errors.structureNodeId ? "error" : ""}`}
                        placeholder="Select node from structure"
                      />
                      <Building2 size={15} className="input-icon" />
                    </div>
                    {errors.structureNodeId && <span className="error-message">{errors.structureNodeId}</span>}
                  </div>

                  <div className="form-group">
                    <label className="form-label">Auto-generated Reference</label>
                    <div className="code-display">{autoGeneratedCode}</div>
                    <span className="input-hint">This will be used if you leave the field above empty</span>
                  </div>
                </div>
              </div>
            </div>
          )}

          <div className="wizard-actions">
            <button
              type="button"
              className="wizard-btn secondary"
              onClick={prevStep}
              disabled={currentStep === 0}
            >
              Back
            </button>
            {currentStep < steps.length - 1 ? (
              <button type="button" className="wizard-btn primary" onClick={nextStep}>
                Next
              </button>
            ) : (
              <button type="submit" className="wizard-btn primary" disabled={submitting}>
                {submitting ? "Creating..." : "Create Staff"}
              </button>
            )}
          </div>
        </form>
      </div>

      <ScopeTreeModal
        isOpen={showStructureModal}
        onClose={() => setShowStructureModal(false)}
        onSelect={handleNodeSelect}
        initialScopeId={formData.structureNodeId}
      />

      {showSuccess && (
        <>
          <div className="success-overlay" />
          <div className="success-message">
            <div className="success-icon"><CheckCircle2 size={38} color="#e0c06a" /></div>
            <div className="success-text">Staff Created Successfully!</div>
            <p>Redirecting to users list...</p>
          </div>
        </>
      )}
    </div>
  );
};

export default AddStaff;