import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { useTranslation } from "react-i18next";
import {
  User, Mail, Lock, Phone, Shield, CheckCircle2, UserPlus, KeyRound,
  Building2, Briefcase, Calendar, Hash
} from "lucide-react";
import userService from "../services/userService";
import { ScopeTreeModal } from "../../university/components/ScopeTreeModal";
import "../styles/userForms.css";

const AddStaff = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const steps = [t("basic_information"), t("account_security"), t("employment_information")];
  const [currentStep, setCurrentStep] = useState(0);
  const [loading, setLoading] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [showSuccess, setShowSuccess] = useState(false);
  const [showStructureModal, setShowStructureModal] = useState(false);

  const [formData, setFormData] = useState({
    staffCode: "",
    nationalId: "",
    nameAr: "",
    nameEn: "",
    email: "",
    password: "",
    confirmPassword: "",
    role: "",
    jobTitle: "",
    structureNodeId: "",
    phoneNumber: "",
    birthDate: "",
  });

  const [roles, setRoles] = useState([]);
  const [autoGeneratedCode, setAutoGeneratedCode] = useState("");
  const [selectedNodeName, setSelectedNodeName] = useState("");
  const [errors, setErrors] = useState({});
  const [checkingEmail, setCheckingEmail] = useState(false);
  const [checkingNationalId, setCheckingNationalId] = useState(false);

  useEffect(() => {
    const loadRoles = async () => {
      setLoading(true);
      try {
        const rolesData = await userService.getRoles();
        setRoles(rolesData);
        setAutoGeneratedCode(`EMP-${Date.now()}`);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    loadRoles();
  }, []);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
    if (errors[name]) setErrors((prev) => ({ ...prev, [name]: "" }));
  };

  const handleNodeSelect = (node) => {
    setFormData((prev) => ({ ...prev, structureNodeId: node.id }));
    setSelectedNodeName(`${node.localizedName || node.name} (${node.type})`);
    setShowStructureModal(false);
    if (errors.structureNodeId) setErrors((prev) => ({ ...prev, structureNodeId: "" }));
  };

  const checkEmailUnique = async (email) => {
    if (!email) return true;
    setCheckingEmail(true);
    try {
      const result = await userService.checkEmailUnique(email, "Staff");
      return result.isUnique;
    } catch {
      return false;
    } finally {
      setCheckingEmail(false);
    }
  };

  const checkNationalIdUnique = async (nationalId) => {
    if (!nationalId) return true;
    setCheckingNationalId(true);
    try {
      const result = await userService.checkNationalIdUnique(nationalId, "Staff");
      return result.isUnique;
    } catch {
      return false;
    } finally {
      setCheckingNationalId(false);
    }
  };

  const validateStep = async () => {
    const newErrors = {};
    if (currentStep === 0) {
      if (!formData.nationalId) newErrors.nationalId = t("field_required");
      else if (formData.nationalId.length !== 14) newErrors.nationalId = t("invalid_national_id");
      else if (!/^\d+$/.test(formData.nationalId)) newErrors.nationalId = t("only_numbers");
      else {
        const unique = await checkNationalIdUnique(formData.nationalId);
        if (!unique) newErrors.nationalId = t("national_id_exists");
      }
      if (!formData.nameAr) newErrors.nameAr = t("field_required");
      if (!formData.email) newErrors.email = t("field_required");
      else if (!/\S+@\S+\.\S+/.test(formData.email)) newErrors.email = t("invalid_email");
      else {
        const unique = await checkEmailUnique(formData.email);
        if (!unique) newErrors.email = t("email_exists");
      }
      if (!formData.birthDate) newErrors.birthDate = t("field_required");
    }
    if (currentStep === 1) {
      if (!formData.password) newErrors.password = t("field_required");
      else if (formData.password.length < 6) newErrors.password = t("password_too_short");
      if (formData.password !== formData.confirmPassword)
        newErrors.confirmPassword = t("passwords_do_not_match");
    }
    if (currentStep === 2) {
      if (!formData.role) newErrors.role = t("field_required");
      if (!formData.structureNodeId)
        newErrors.structureNodeId = t("field_required");
    }
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const nextStep = async () => {
    if (await validateStep()) setCurrentStep((prev) => prev + 1);
  };
  const prevStep = () => setCurrentStep((prev) => prev - 1);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!(await validateStep())) return;
    setSubmitting(true);
    const finalEmployeeCode = formData.staffCode.trim() || autoGeneratedCode;
    const payload = {
      employeeCode: finalEmployeeCode,
      nameAr: formData.nameAr,
      nameEn: formData.nameEn || formData.nameAr,
      nationalId: formData.nationalId,
      birthDate: formData.birthDate,
      phoneNumber: formData.phoneNumber || null,
      email: formData.email,
      password: formData.password,
      confirmPassword: formData.confirmPassword,
      role: formData.role,
      jobTitle: formData.jobTitle || null,
      structureNodeId: formData.structureNodeId,
    };
    try {
      await userService.createStaff(payload);
      setShowSuccess(true);
      setTimeout(() => navigate("/admin/users"), 1600);
    } catch (err) {
      alert(err.response?.data?.message || err.message);
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) return <div className="form-loading">{t("loading")}</div>;

  return (
    <div className="add-user-page">
      <div className="page-container compact-wizard">
        <div className="page-header compact-header">
          <div className="header-content">
            <div className="header-icon"><UserPlus size={22} /></div>
            <div className="header-text">
              <h1>{t("add_staff")}</h1>
              <div className="gold-line" />
              <p>{t("create_new_staff_account")}</p>
            </div>
          </div>
        </div>

        <div className="wizard-steps">
          {steps.map((step, idx) => (
            <button
              key={step}
              type="button"
              className={`wizard-step ${idx === currentStep ? "active" : ""} ${idx < currentStep ? "done" : ""}`}
              onClick={() => setCurrentStep(idx)}
            >
              <span>{idx + 1}</span>
              {step}
            </button>
          ))}
        </div>

        <form onSubmit={handleSubmit}>
          {currentStep === 0 && (
            <div className="form-card wizard-card">
              <div className="form-header">
                <div className="form-icon"><User size={18} color="#e0c06a" /></div>
                <div className="form-title-wrapper"><h3>{t("basic_information")}</h3><p>{t("personal_details")}</p></div>
              </div>
              <div className="form-body">
                <div className="form-grid compact-grid">
                  <div className="form-group">
                    <label className="form-label">{t("national_id")} *</label>
                    <div className="input-wrapper">
                      <input type="text" name="nationalId" value={formData.nationalId} onChange={handleChange} className={`form-input ${errors.nationalId ? "error" : ""}`} placeholder={t("14_digit_national_id")} maxLength="14" />
                      <User size={15} className="input-icon" />
                    </div>
                    {checkingNationalId && <span className="input-hint">{t("checking")}</span>}
                    {errors.nationalId && <span className="error-message">{errors.nationalId}</span>}
                  </div>
                  <div className="form-group">
                    <label className="form-label">{t("full_name_arabic")} *</label>
                    <div className="input-wrapper">
                      <input type="text" name="nameAr" value={formData.nameAr} onChange={handleChange} className={`form-input ${errors.nameAr ? "error" : ""}`} placeholder={t("full_name_arabic_placeholder")} />
                      <User size={15} className="input-icon" />
                    </div>
                    {errors.nameAr && <span className="error-message">{errors.nameAr}</span>}
                  </div>
                  <div className="form-group">
                    <label className="form-label">{t("full_name_english")}</label>
                    <div className="input-wrapper">
                      <input type="text" name="nameEn" value={formData.nameEn} onChange={handleChange} className="form-input" placeholder={t("full_name_english_placeholder")} />
                      <User size={15} className="input-icon" />
                    </div>
                  </div>
                  <div className="form-group">
                    <label className="form-label">{t("email")} *</label>
                    <div className="input-wrapper">
                      <input type="email" name="email" value={formData.email} onChange={handleChange} className={`form-input ${errors.email ? "error" : ""}`} placeholder="staff@university.edu" />
                      <Mail size={15} className="input-icon" />
                    </div>
                    {checkingEmail && <span className="input-hint">{t("checking")}</span>}
                    {errors.email && <span className="error-message">{errors.email}</span>}
                  </div>
                  <div className="form-group">
                    <label className="form-label">{t("date_of_birth")} *</label>
                    <div className="input-wrapper">
                      <input type="date" name="birthDate" value={formData.birthDate} onChange={handleChange} className={`form-input ${errors.birthDate ? "error" : ""}`} />
                      <Calendar size={15} className="input-icon" />
                    </div>
                    {errors.birthDate && <span className="error-message">{errors.birthDate}</span>}
                  </div>
                  <div className="form-group">
                    <label className="form-label">{t("phone")}</label>
                    <div className="input-wrapper">
                      <input type="tel" name="phoneNumber" value={formData.phoneNumber} onChange={handleChange} className="form-input" placeholder={t("phone_number")} />
                      <Phone size={15} className="input-icon" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}

          {currentStep === 1 && (
            <div className="form-card wizard-card">
              <div className="form-header">
                <div className="form-icon"><KeyRound size={18} color="#e0c06a" /></div>
                <div className="form-title-wrapper"><h3>{t("account_security")}</h3><p>{t("set_password")}</p></div>
              </div>
              <div className="form-body">
                <div className="form-grid compact-grid two-cols">
                  <div className="form-group">
                    <label className="form-label">{t("password")} *</label>
                    <div className="input-wrapper">
                      <input type="password" name="password" value={formData.password} onChange={handleChange} className={`form-input ${errors.password ? "error" : ""}`} placeholder={t("minimum_6_characters")} />
                      <Lock size={15} className="input-icon" />
                    </div>
                    {errors.password && <span className="error-message">{errors.password}</span>}
                  </div>
                  <div className="form-group">
                    <label className="form-label">{t("confirm_password")} *</label>
                    <div className="input-wrapper">
                      <input type="password" name="confirmPassword" value={formData.confirmPassword} onChange={handleChange} className={`form-input ${errors.confirmPassword ? "error" : ""}`} placeholder={t("re_enter_password")} />
                      <Lock size={15} className="input-icon" />
                    </div>
                    {errors.confirmPassword && <span className="error-message">{errors.confirmPassword}</span>}
                  </div>
                </div>
              </div>
            </div>
          )}

          {currentStep === 2 && (
            <div className="form-card wizard-card">
              <div className="form-header">
                <div className="form-icon"><Briefcase size={18} color="#e0c06a" /></div>
                <div className="form-title-wrapper"><h3>{t("employment_information")}</h3><p>{t("role_job_title_structure_code")}</p></div>
              </div>
              <div className="form-body">
                <div className="form-grid compact-grid">
                  <div className="form-group">
                    <label className="form-label">{t("staff_code")}</label>
                    <div className="input-wrapper">
                      <input type="text" name="staffCode" value={formData.staffCode} onChange={handleChange} className="form-input" placeholder={t("leave_empty_to_auto_generate")} />
                      <Hash size={15} className="input-icon" />
                    </div>
                    <span className="input-hint">{t("optional_auto_generated")}</span>
                  </div>
                  <div className="form-group">
                    <label className="form-label">{t("role")} *</label>
                    <div className="input-wrapper">
                      <select name="role" value={formData.role} onChange={handleChange} className={`form-select ${errors.role ? "error" : ""}`}>
                        <option value="">{t("select_role")}</option>
                        {roles.map((r) => (<option key={r.id} value={r.id}>{r.name}</option>))}
                      </select>
                      <Shield size={15} className="input-icon" />
                    </div>
                    {errors.role && <span className="error-message">{errors.role}</span>}
                  </div>
                  <div className="form-group">
                    <label className="form-label">{t("job_title")}</label>
                    <div className="input-wrapper">
                      <input type="text" name="jobTitle" value={formData.jobTitle} onChange={handleChange} className="form-input" placeholder={t("e_g_department_head")} />
                      <Briefcase size={15} className="input-icon" />
                    </div>
                  </div>
                  <div className="form-group">
                    <label className="form-label">{t("structure_node")} *</label>
                    <div className="input-wrapper">
                      <input type="text" value={selectedNodeName} readOnly onClick={() => setShowStructureModal(true)} className={`form-input ${errors.structureNodeId ? "error" : ""}`} placeholder={t("select_node_from_structure")} />
                      <Building2 size={15} className="input-icon" />
                    </div>
                    {errors.structureNodeId && <span className="error-message">{errors.structureNodeId}</span>}
                  </div>
                  <div className="form-group">
                    <label className="form-label">{t("auto_generated_reference")}</label>
                    <div className="code-display">{autoGeneratedCode}</div>
                    <span className="input-hint">{t("auto_generated_hint")}</span>
                  </div>
                </div>
              </div>
            </div>
          )}

          <div className="wizard-actions">
            <button type="button" className="wizard-btn secondary" onClick={prevStep} disabled={currentStep === 0}>{t("back")}</button>
            {currentStep < steps.length - 1 ? (
              <button type="button" className="wizard-btn primary" onClick={nextStep}>{t("next")}</button>
            ) : (
              <button type="submit" className="wizard-btn primary" disabled={submitting}>{submitting ? t("creating") : t("create_staff")}</button>
            )}
          </div>
        </form>
      </div>

      <ScopeTreeModal isOpen={showStructureModal} onClose={() => setShowStructureModal(false)} onSelect={handleNodeSelect} initialScopeId={formData.structureNodeId} />

      {showSuccess && (
        <>
          <div className="success-overlay" />
          <div className="success-message">
            <div className="success-icon"><CheckCircle2 size={38} color="#e0c06a" /></div>
            <div className="success-text">{t("staff_created_success")}</div>
            <p>{t("redirecting")}</p>
          </div>
        </>
      )}
    </div>
  );
};

export default AddStaff;